spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${FAMILY_MYSQL_HOST:localhost}:3306/${DATABASE:logicea}
    username: ${MS_USERNAME:root}
    password: ${MS_PASSWORD:passwd123}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-version: 1
    schemas: "public"
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: true
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always
    include-stacktrace: never